name: Release

on:
  push:
    branches:
      - release
      - staging

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release
        uses: eco-trip/semantic-release-action@v1.0
        with:
          token: ${{ secrets.MEBBOT }}
